### ISSUE TITLE
This is amazing

### ISSUE THREAD

**Issue by aarondfrancis** [Wyess/will2svg#1]
This is wildly helpful for my new Wacom Paper tablet. I originally exported the SVG from Inkspace and was super disappointed it wasn't a center-line path, but then I found this thread (https://forum.affinity.serif.com/index.php?/topic/50924-wacom-bamboo-slate-to-affinity-designer-svg-export-issue/&page=2) and that lead me here. Thanks so much!

**Comment by XsavciX** [comment]
Excellent. This is all I want.
Thank you very much Wyess.
