### ISSUE TITLE
SVG output is 90 degrees rotated

### ISSUE THREAD

**Issue by aarondfrancis** [Wyess/will2svg#2]
Using a WILL file from the Wacom Paper tablet. Any ideas how to fix that?

**Comment by Wyess** [comment]
I guess you are using the tablet in landscape position, right? If that is the case, the transformation matrix needs to be set correctly to rotate the canvas 90 degrees. I've just modified the scripts and the output SVG is now correctly rotated. Could you test it in your environment?
