### ISSUE TITLE
problem with Bamboo Slate a4

### ISSUE THREAD

**Issue by kaushik-mrg** [Wyess/will2svg#3]
Dear Sir,
Thankyou for your code.
I am sorry its not working for me as i am using Bamboo Slate a4 (here in section/media, we have Strokes not path) can you suggest how we can proceed

**Comment by Wyess** [comment]
Hello there! Could you provide me with a sample *.will file so I can debug?

**Comment by kaushik-mrg** [comment]
Dear sir,
Thank you very much for your reply.
I am attaching herewith a sample will file for your reference.

**Comment by Wyess** [comment]
Seems like an attachment file is lost when you reply via email. Could you try attaching the file on the Github's comment section?

**Comment by kaushik-mrg** [comment]
Ok sir

**Comment by kaushik-mrg** [comment]
[WCM0021.zip](https://github.com/Wyess/will2svg/files/4415801/WCM0021.zip)
I am unable to upload .will due to restriction in upload, so renamed .will to .zip
please rename the same to .will for use

**Comment by kaushik-mrg** [comment]
[WCM0021.zip](https://github.com/Wyess/will2svg/files/4415812/WCM0021.zip)
compressed for ready reference.
it is going in infinite loop. no output, no error.

**Comment by kaushik-mrg** [comment]
Uploaded sir

**Comment by Wyess** [comment]
![image](https://user-images.githubusercontent.com/714174/78232581-69e81c80-750f-11ea-8280-dd0106c0eed8.png) Thanks to your report I was able to find a bug in my code. I fixed it and your .will file can now be decoded like this. Could you update the code and see if it works on your computer?

**Comment by kaushik-mrg** [comment]
Yes sir many many thankx for the update.
